import {
  date,
  doublePrecision,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

export const samples = pgTable("samples", {
  id: uuid("id").primaryKey().defaultRandom(),
  alias: text("alias").unique().notNull(),
  locality: text("locality"),
  description: text("description"),
  latitude: doublePrecision("latitude"),
  latitudeUnit: text("latitude_unit"),
  longitude: doublePrecision("longitude"),
  longitudeUnit: text("longitude_unit"),
  physicalCoordinates: text("physical_coordinates"),
  countryCode: text("country_code"),
  higherGeography: text("higher_geography"),
  elevation: doublePrecision("elevation"),
  elevationUnit: text("elevation_unit"),
  depth: doublePrecision("depth"),
  depthUnit: text("depth_unit"),
  collectionDate: date("collection_date"),
  projectName: text("project_name"),
  samplingProtocol: text("sampling_protocol"),
  preparationType: text("preparation_type"),
  coreLength: doublePrecision("core_length"),
  coreLengthUnit: text("core_length_unit"),
  storageLocation: text("storage_location"),
  custodian: text("custodian"),
  collectedBy: text("collected_by"),
  eventId: text("event_id"),
  recordedBy: text("recorded_by"),
  institutionCode: text("institution_code"),
  ownerInstitutionCode: text("owner_institution_code"),
  age: doublePrecision("age"),
  ageUnit: text("age_unit"),
  ageUncertainty: doublePrecision("age_uncertainty"),
  ageUncertaintyUnit: text("age_uncertainty_unit"),
  basalAge14CBP: doublePrecision("basal_age_14C_BP"),
  basalAge14CBPUnit: text("basal_age_14C_BP_unit"),
  basalAgeCalBP: doublePrecision("basal_age_cal_BP"),
  basalAgeCalBPUnit: text("basal_age_cal_BP_unit"),
  oldestSampleAgeCalBP: doublePrecision("oldest_sample_age_cal_BP"),
  oldestSampleAgeCalBPUnit: text("oldest_sample_age_cal_BP_unit"),
  bibliographicCitation: text("bibliographic_citation"),
  associatedReferences: text("associated_references"),
  occurrenceRemarks: text("occurrence_remarks"),
  eventRemarks: text("event_remarks"),
  source: text("source"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});
